version: '3.8' # refers docker file syntax version

services:
  dynamic-model-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # optional: only if you want live reload on code changes
    environment:
      - PYTHONPATH=/app  # ensure Python can find the app module

# railway does not use compose